---
- name: restart mysql
  service: name=mysql state=restarted
  
- name: enable apache site
  shell: /usr/sbin/a2dissite 000-default && /usr/sbin/a2ensite default-wp
  notify: restart apache

- name: restart apache
  service:
    name=apache2
    state=restarted
    enabled=yes
