---
- hosts: localhost
  user: cloud
  become: yes
  tasks:
  - name: packages installed
    apt:
      pkg={{ item }}
      state=present
    with_items:
      - python-django-tagging
      - python-django
      - python-zope.interface
      - python-cairo
      - python-twisted
      - apache2

  - name: packages installed
    apt:
      pkg={{ item }}
     state=present
    with_items:
      - apache2.2-common
      - apache2-mpm-prefork
      - apache2-utils
      - libexpat1
      - ssl-cert
      - libapache2-mod-wsgi
       #--enablerepo=epel

  - name: Creates directory
    file: path=/tmp/graphite state=directory

#download  package

  - name: download carbon and force basic auth
    get_url:
      url=https://launchpad.net/graphite/0.9/0.9.10/+download/carbon-0.9.10.tar.gz
      dest=/tmp/graphite/carbon-0.9.10.tar.gz
      force_basic_auth=yes

  - name: download whisper and force basic auth
    get_url:
      url=https://launchpad.net/graphite/0.9/0.9.10/+download/whisper-0.9.10.tar.gz
      dest=/tmp/graphite/carbon-0.9.10.tar.gz
      force_basic_auth=yes

  - name: download graphite-web and force basic auth
    get_url:
      url=https://launchpad.net/graphite/0.9/0.9.10/+download/graphite-web-0.9.10.tar.gz
      dest=/tmp/graphite/carbon-0.9.10.tar.gz
      force_basic_auth=yes

# Unarchive  packages

  - name: unarchive carbon
    unarchive:
      src=/tmp/graphite/carbon-0.9.10.tar.gz
      dest=/tmp/graphite/carbon-0.9.10

  - name: unarchive whisper
    unarchive:
      src=/tmp/graphite/whisper-0.9.10.tar.gz
      dest=/tmp/graphite/whisper-0.9.10

  - name: unarchive graphite-web
    unarchive:
      src=/tmp/graphite/graphite-web-0.9.10.tar.gz
      dest=/tmp/graphite/graphite-web-0.9.10

# Install packages

  - name: Install packages
    args:
      chdir: /tmp/graphite/
      executable: /bin/bash
    shell: |
      cd graphite-web-0.9.10
      sudo python setup.py install
      cd ..
      cd whisper-0.9.10
      sudo python setup.py install
      cd ..
      cd carbon-0.9.10
      sudo python setup.py install

# Configuration Carbon
  - name: config carbon
    copy:
      src=/opt/graphite/conf/carbon.conf.example
      dest=/opt/graphite/conf/carbon.conf
      #owner=
      #group=
      #mode=0644

  - name: config carbon2
    copy:
      src=/opt/graphite/conf/storage-schemas.conf.example
      dest=/opt/graphite/conf/storage-schemas.conf
      #owner=
      #group=
      #mode=0644

  #Configuration de la webapp

  - name: conf web app
    file: path=/etc/httpd/conf.d/wsgi.conf state=absent
      #owner=foo
      #group=foo


  - name: conf web app2
    copy:
      src=/opt/graphite/examples/example-graphite-vhost.conf
      dest=/etc/httpd/conf.d/vhost-graphite.conf
      #owner=
      #group=
      #mode=0644

  - name: conf web app3
    copy:
      src=/opt/graphite/conf/graphite.wsgi.example
      dest=/opt/graphite/conf/graphite.wsgi
      #owner=
      #group=
      #mode=0644

  - name: conf web app4
    copy:
      src=/opt/graphite/webapp/graphite/local_settings.py.example
      dest=/opt/graphite/webapp/graphite/local_settings.py
      #owner=
      #group=
      #mode=0644

  - name: demarrage services
    args:
      #chdir: /etc/openvpn/
      executable: /bin/bash
    shell: |
      sudo python /opt/graphite/webapp/graphite/manage.py syncdb --noinput
      sudo service httpd start
      sudo ./opt/graphite/bin/carbon-cache.py start
