---

# Part 1: download packages

  - name: Update Upgrade
    apt: update_cache=true upgrade=full

  - name: Download collectd
    apt:
      pkg={{ item }}
      state=present
    with_items:
      - collectd
      - urllib3

  - name: Add source influxdb
    args:
      executable: /bin/bash
    shell: |
      echo "deb https://repos.influxdata.com/debian jessie stable" > /etc/apt/sources.list.d/influxdb.list
      curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -

  - name: Add source grafana
    args:
      executable: /bin/bash
    shell: |
      sudo echo 'deb https://packagecloud.io/grafana/stable/debian/ wheezy main' >> /etc/apt/sources.list
      curl https://packagecloud.io/gpg.key | sudo apt-key add -

  - name: Update Upgrade
    apt: update_cache=true upgrade=full

  - name: Download grafana & influxdb
    apt:
      pkg={{ item }}
      state=present
    with_items:
      - apt-transport-https
      - grafana
      - influxdb

# Part 2: Configuration

  - name: Collectd configuration 1
    replace:
      dest=/etc/collectd/collectd.conf
      regexp='#LoadPlugin network'
      replace='LoadPlugin network'

  - lineinfile: dest=/etc/collectd/collectd.conf line="<Plugin network>"
  - lineinfile: dest=/etc/collectd/collectd.conf line="  Server "127.0.0.1" "25826""
  - lineinfile: dest=/etc/collectd/collectd.conf line="<Plugin>"

  - name: Collectd configuration 1
    replace:
      dest=/etc/collectd/collectd.conf
      regexp='<Plugin>'
      replace='</Plugin>'


  - name: Influxdb configuration
    replace:
      dest=/etc/opt/influxdb/influxdb.conf
      regexp='^\[collectd\](\n.*){4}'
      replace='[collectd]\n  enabled = true\n  bind-address = ":25826"\n  database = "collectd_db"\n  typesdb = "/usr/share/collectd/types.db"'


# Part 3: Starting services

  - name: restart collectd
    service: name=collectd state=restarted

  - name: restart influxdb
    service: name=influxdb state=restarted

  - name: restart grafana-server
    service: name=grafana-server state=restarted

 # Part 4: Adding datasources

  - name: add grafana datasource
    args:
      executable: /bin/bash
    shell: |
      curl 'http://admin:admin@127.0.0.1:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"name":"influx","type":"influxdb","url":"http://localhost:8086","access":"proxy","isDefault":true,"database":"collectd_db","user":"root","password":"root"}'
